### ISSUE TITLE
Update Index links for "Backend Design" in documentation

### ISSUE THREAD

**Issue by aminamos** [CouncilDataProject/cdptools#113]
## Description
*A clear description of the bug*
Technically "Transcript Format" and "Deploying and Running CDP Pipelines" have the same issue, but clicking an item in the index list doesn't bring the user to that section on the page. 

## Expected Behavior
*What did you expect to happen instead?*
Brought to Pipelines section, actual link is https://councildataproject.github.io/cdptools/system_design.html#id9

[system_design.md](https://github.com/CouncilDataProject/cdptools/blob/master/docs/system_design.md) has the correct link, maybe something is up with [system_design.rst](https://github.com/CouncilDataProject/cdptools/blob/master/docs/system_design.rst)? I do not have experience with these tools, and am new to this overall.

## Reproduction
*A minimal example that exhibits the behavior.*
1. Navigate to https://councildataproject.github.io/cdptools/system_design.html
2. Click "Pipelines" in the index
3. URL in address bar changes to https://councildataproject.github.io/cdptools/system_design.html#pipelines
4. Position on the page stays the same

## Environment
*Any additional information about your environment*

**Comment by JacksonMaxfield** [comment]
Yea I have been frustrated by this as well. I'm 90% sure it has something to do with Sphinx doc generation. Most of the links _should_ work properly unless there is a typo in the ref or something. For example, if you hover of the item in the tree on the left side the actual ref is there, usually it is like `#id2` or similar. This is Sphinx generated and I am not sure why they are replacing the value.
