### ISSUE TITLE
Store image of first face present in video as thumbnail

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/cdptools#117]
## Use Case
*Please provide a use case to help us understand your request in context*
All event card designs proposed all use the idea of displaying the first face found in the video as a part of the event card as this is usually the chair of the committee.

## Solution
*Please describe your ideal solution*
..... https://realpython.com/face-recognition-with-python/ ??? Maybe

## Alternatives
*Please describe any alternatives you've considered, even if you've dismissed them*

**Comment by tohuynh** [comment]
seattlechannel.org does store images of thumbnails, though they may be too small?
![image](https://user-images.githubusercontent.com/37560480/71788410-d74ee480-2fd6-11ea-9b7e-ec9d9827ef20.png)
https://www.seattlechannel.org/images/seattlechannel/videos/2019/Q4/council_121619.jpg
