### ISSUE TITLE
Write Bellevue Event Scraper

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/cdptools#120]
## Use Case
*Please provide a use case to help us understand your request in context*
Now that the cost of running the server for Seattle is so low, let's expand and deploy in Bellevue. The first step is to write a scraper for gathering their events.

## Solution
*Please describe your ideal solution*
From looking at their services, everything _should_ be available through legistar and so the legistar utils submodule should do most of the work and we may just need a bit of configuration to get it working for Bellevue.

[Legistar](https://bellevue.legistar.com/Calendar.aspx)

*Note:* we will need to figure out the Bellevue granicus "client-name"

## Alternatives
*Please describe any alternatives you've considered, even if you've dismissed them*

**Comment by aminamos** [comment]
I sent an email to Bellevue's City Clerk requesting the client-name.

**Comment by JacksonMaxfield** [comment]
Yea. Please keep me updated on this. I tried calling them but they didn't really know what I was talking about. Or you can cc jmaxfieldbrown@gmail.com
