### ISSUE TITLE
Experiment with different transcript confidence computations (GoogleCloudSRModel)

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/cdptools#41]
Currently transcript confidence is computed by simply averaging the confidence of every returned sentence. In my opinion, this is inaccurate because in the case when no words/ sentences are returned in the `alternatives` block, there should be a negative weight applied.

A simple solution to try would be to weight the confidence by percent of transcript returned. We know the audio length, we can sum the length of the returned sections thanks to [gh-32] (timestamped transcripts); so confidence under using this would be:

`Adjusted Confidence = (Sum(L_s) / L_a) * Avg(C_s)`

L_s = length of sentence (for each sentence s)
L_a = length of audio
C_s = confidence of sentence (for each sentence s)

**Comment by nniiicc** [comment]
Not sure I follow. Transcript confidence is the certainty that a transcription occurred, or that it was accurate? 

>  simply averaging the confidence of every returned sentence

**Comment by JacksonMaxfield** [comment]
Sentence confidence is googles confidence that the returned sentence transcription is accurate. I am generating transcript confidence by averaging all the returned sentence confidences. But commonly, as you know, sentences are missing so that average is actually higher than is should be imo.

**Comment by JacksonMaxfield** [comment]
Closing for now. I don't particularly think either calculation is the _best_. The current calculation is really simple, but the proposed misses the fact that speaking may begin after the audio begins, and end before the audio ends. Both calculations would be incorrect in that sense.
