### ISSUE TITLE
Add SingleEventGatherPipeline

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/cdptools#76]
In certain cases it would be incredibly valuable to have the CDP system for viewing.

Specifically things like election coverage and special events like press conferences from city council members.

Configs would only need `uri` and event `description` along with the normal database / file store / module configs.

**Comment by nniiicc** [comment]
Because of the variability in events it will be hard to systematize a feed... Maybe have a "suggested  a related event" page where someone can submit a video or audio link, and CDP can moderate what gets transcribed and published.
